version: "3.1"
services:
  dev-zookeeper:
    image: wurstmeister/zookeeper
    container_name: dev-zookeeper
    ports:
      - "2181:2181"
  dev-kafka:
    image: wurstmeister/kafka
    container_name: dev-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper:2181