version: "3.1"
services:
  customer-service:
    container_name: customer-service
    image: customer-service
    build: ./customer-service
    ports:
    - "8080:8080"
    depends_on:
      - customer-db
  customer-db:
    container_name: customer-db
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CustomerDB
  order-service:
    container_name: order-service
    image: order-service
    build: ./order-service
    ports:
    - "8081:8081"
    depends_on:
      - order-db
  order-db:
    container_name: order-db
    image: postgres
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=OrderDB