version: "3.1"
services:
  customer-service:
    container_name: customer-service
    image: customer-service
    build: ./customer
    ports:
    - "8080:8080"
    depends_on:
      - dev-postgres
  dev-postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CustomerDB